// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedTask } from "./SharedTask";
import type { UserData } from "./UserData";

export type SharedTaskResponse = { task: SharedTask, user: UserData | null, };
