// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserData = { user_id: string, first_name: string | null, last_name: string | null, username: string | null, };
